name: Node CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Install Node.js
      uses: actions/setup-node@v1
      with:
        node-version: '10.x'
    - name: install ionic
      run: npm install -g @ionic/cli
    - name: Install npm dependencies
      run: npm install
    - name: Run build task
      run: ionic build --prod
    - name: Deploy to Server
#       uses: easingthemes/ssh-deploy@v2.0.9
      uses: appleboy/scp-action@0.0.7
      env:
          HOST: ${{ secrets.REMOTE_HOST }}
          USERNAME: ${{ secrets.REMOTE_USER }}
          PORT: ${{ secrets.REMOTE_PORT }}
          KEY: ${{ secrets.SSH_PRIVATE_KEY }}
      with:
          source: "./www/"
          target: ${{ secrets.REMOTE_TARGET }}
          strip_components: 3 # this is important
#           SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
# #           ARGS: "-rltgoDzvO --delete"
#           ARGS: "-rltgoDzvO"
#           SOURCE: "www/"
#           REMOTE_HOST: ${{ secrets.REMOTE_HOST }}
#           REMOTE_USER: ${{ secrets.REMOTE_USER }}
#           REMOTE_PORT: ${{ secrets.REMOTE_PORT }}
#           TARGET: ${{ secrets.REMOTE_TARGET }}
