# This is a basic workflow to help you get started with Actions

name: CI
on: push
jobs:
  repo-sync:
    runs-on: ubuntu-latest
    steps:
    - name: repo-sync
      uses: wei/git-sync@v1
      env:
        SOURCE_REPO: "https://github.com/daxslab/molote-client.git"
        SOURCE_BRANCH: "master"
        DESTINATION_REPO: ${{ secrets.ACTION_DESTINATION_REPO }}
        DESTINATION_BRANCH: "master"
      with:
        args: $SOURCE_REPO $SOURCE_BRANCH $DESTINATION_REPO $DESTINATION_BRANCH
